FROM python:3.6.4-alpine3.7@sha256:10bd7a59cfac2a784bedd1e6d89887995559f00b61f005a101845ed736bed779
RUN apk add --no-cache git

ENV PIP_DISABLE_PIP_VERSION_CHECK True
ENV PIP_NO_CACHE_DIR False
ENV PYTHONUNBUFFERED True

WORKDIR /docs
RUN python -m pip install sphinx-multiversion sphinx_rtd_theme
CMD ["sphinx-multiversion", "docs", "_build"]
